name: Docker CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: '0 0 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Prepare kreato/builder
        run: |
            mkdir /tmp/docker.tmp
            mv $GITHUB_WORKSPACES/Dockerfile /tmp/docker.tmp/
            cd /tmp/docker.tmp || exit 1
            apt update
            apt install wget unzip -y
            wget https://nightly.link/kreatolinux/nyaastrap/workflows/main/master/builder-rootfs.zip
            unzip builder-rootfs.zip
            cd builder-rootfs || exit 1
            tar -xvpf kreato-linux-builder-*.tar.gz -C "/tmp/docker.tmp"
            rm -rf builder-rootfs.zip builder-rootfs
             
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push kreato/builder
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kreato/builder:latest
            
